---
- name: Configure host netplan
  become: true
  hosts: servers 
  vars:
    cvm_address: '{{ ansible_host }}/24'

  tasks:

    - name: copy netplan file
      template: src=templates/51-config.yml.j2 dest=/etc/netplan/51-config.yaml
      notify: apply netplan

  handlers:

    - name: apply netplan
      shell: netplan apply

- name: Configure ssh
  become: true
  hosts: servers 
  vars:
    newpassword: 'admin123'

  tasks:

    - name: copy netplan file
      copy: src=files/sshd_config dest=/etc/ssh/sshd_config
      notify: apply ssh

    - name: change root password
      user:
        name: root
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"

  handlers:

    - name: apply ssh
      service: 
        name: ssh
        state: restarted


